### ISSUE TITLE
Nette 2.4 issue

### ISSUE THREAD

**Issue by camohub** [NasExt/Forms#1]
Zdravím,
updatujem jeden projekt, ktorý používa NasExt/Forms a na Nette 2.4 mi to hádže error kôli funkcii callback v metode register:

    /**
	 * Adds addRangeSlider() method to \Nette\Forms\Form
	 */
	public static function register()
	{
		Container::extensionMethod('addRangeSlider', callback(__CLASS__, 'addRangeSlider'));
	}

keď to prepíšem na

    Nette\Utils\Callback::closure(__CLASS__, 'addRangeSlider')

tak to funguje.

**Comment by duskohu** [comment]
Zdravím, to je preto lebo tato komponenta je už staršieho dáta a nejaký cas som ju neaktualizoval.
Aký error ti to vypisuje?

**Comment by camohub** [comment]
Sorry v prvom komente bola chyba(opravené). Error je "callback() is deprecated; use native PHP callback." 
Malo by sa použiť Nette\Utils\Callback::closure(), alebo obyčajné pole [ **CLASS**, 'addRangeSlider' ].

**Comment by camohub** [comment]
Teraz som narazil na ďalší error: 
**Declaration of Nextras\Forms\Controls\OptionList::getControlPart() should be compatible with Nette\Forms\Controls\BaseControl::getControlPart()**
V súbore nextras\forms\src\Controls\OptionList.php:27

```
class OptionList extends BaseControl implements \IteratorAggregate
{
...
```

S týmto si naozaj neviem rady. Dalo by sa to prosím ťa fixnút? 
EDIT: Súvisí to s http://stackoverflow.com/questions/3115388/declaration-of-methods-should-be-compatible-with-parent-methods-in-php

Tu som našiel možné riešenie http://stackoverflow.com/questions/3115388/declaration-of-methods-should-be-compatible-with-parent-methods-in-php/9243127#9243127

V podstate daná metóda v child class nemôže mať viac povinných parametrov ako metóda v parent class. Stačilo by teda  urobiť z povinného parametra nepovinný(a očekovať to až v kóde metódy). Tj.

```
public function getControlPart($key = NULL)
```

To isté robí aj getLabelPart().  Tak isto aj v triede MultiOptionList.php

Skúšal som to u seba načierno fixnúť a funguje to.

**Comment by duskohu** [comment]
No táto komponenta nebola nejaký čas udržiavaná, pozriem sa na to.

**Comment by camohub** [comment]
Díky.

**Comment by duskohu** [comment]
@camohub Skus, a daj vediet ci je to ok.

**Comment by camohub** [comment]
Som si až teraz všimol, že ten druhý error sa týka úplne iného balíčka. To si asi nefixoval. Tento balíček funguje. Díky.

**Comment by duskohu** [comment]
Aky balicek? ked moj, napis prosim Issue

**Comment by camohub** [comment]
Nextras\Forms\Controls\OptionList::getControlPart() 
NasExt som yamenil s Nextras.
